name = "website-monitor"
type = "javascript"

account_id = "95be1f4d32426a2e7b725878fc422ad9"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-06-04"

kv_namespaces = [
  { binding = "WEBSITES", id = "d2cb2383c14d4f37ae811fdc5812c12d" }
]

[triggers]
crons = ["*/5 * * * *"]
